Replanteo proyecto como servicio y usuarios finales
migueorg/One-touch-music-streaming-TFG-ETSIIT pull request #25
Opened 2023-04-19 10:44 UTC by migueorg

Con el fin de no sobrecargar el PR #15 en este PR se trabaja sobre la rama `documentación-inicial`.

Se han replanteado, corregido y modificado:
- Objetivos del proyecto 5d9607368dab59ac4e46cfe6b599f273ce4f578f
- Personajes y sus User Journeys c43fb90ee2c860d67f26adcd0cfd55ec02b2724f y 1fdbb0ac595a5ed2e08299be5e990d57f02d310d
- Historias de usuario 0c7895e103340f6359d52237dfe83fdde89e337c
- Milestones 0df88cf4e749cbd9973bc94e5a9f98125ebc92a8

Además atendiendo al [comentario](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/15#discussion_r1161463859) en el PR #15 se ha configurado el editor para que divida las líneas, con el fin de falicitar el comentar por línea en las revisiones.

También se ha cambiado las HU y los Milestones en el repositorio.

2023-04-26 12:19 UTC, JJ requested changes
Has avanzado bastante, y se van aclarando también las cosas poco a poco. Pero trata de aclararlas un poco más, y ya estaría.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
>  \section{Descripción del Problema}
Usar mayúsculas De Aquella Manera es peligroso porque hay que estar muy atento para hacerlo correctamenTe. Yo lo evitaría.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Otra opción sería emplear un asistente virtual (\emph{Alexa, Google Assistant,
En el planteamiento del problema sería conveniente que fueras breve, con algún ejemplo si acaso. Esta descripción más extensa deberías dejarlo para el estado del arte, o más tarde en la introducción.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +poder brindar dicha sensación de continuidad al sistema operativo \emph{Android}
Yo especificaría un poco menos y un poco más. Por ejemplo, hablar de dispositivos de menos coste con un ecosistema abierto. Fijándote en el coste tendrás la versión mínima del JDK de Android que vas a usar, por ejemplo. Un poco más podría ser la antigüedad, que una vez más te fija la versión mínima de Android.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\emph{HomePod}.
Lo mismo, especifica qué tienen que tener los altavoces. ¿Bluetooth? ¿Wifi? ¿NFC?

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    reproduciendo en el dispositivo Android hasta el dispositivo que haga de
No digas Android.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    el altavoz ha de poder realizarse sin interactuar con menús. (Se entiende
no digas nada de la Raspberry Pi. Son detalles de implementación. Has dicho arriba un dispositivo que no sea HomePod. Di qué características tiene y listo.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item El coste final del producto debe estar por debajo de los 349€, el cual
Igual, especifica el precio de qué. Fíjate que hasta este momento no tengo muy claro si
1. Vas a crear un HomePod de bajo coste
2. Vas a crear un programa que pueda trabajar con chismes basados en un ordenador con alguna característica
3. Vas a crear un programa que pueda trabajar con altavoces existentes.

Puede ser que sean las tres cosas, pero en ese caso tienes que dejarlo muy claro; el contexto es siempre muy importante.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    lo que quiere hacer de forma muy mascada para que le consigan entender
NO tengo muy claro cuál es el problema de esta persona. Entiendo que busca una aplicación para su móvil que trabaje con las automatizaciones que mencionas, pero deberías dejarlo un poco más claro.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item María, 55 años, es audiófila desde pequeña y siempre le ha gustado
Tampoco tengo muy claro qué es lo que se busca aquí. Una vez más, parece que, como ya tiene altavoces, querría aprovechar los altavoces. Estamos un paso por debajo del anterior, que posiblemente quiera trabajar con equipos de estos inteligentes.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item El Piso de Olga es un grupo de jóvenes de entre 20 y 25 años que están
Tendrías que escribir un user journey muy claro para esto, porque en mi piso ya nos peleábamos para ver el canal 1 y el 2 de televisión. No tengo muy claro cuál es el contexto aquí, si es que uno quiere llegar con el móvil, dar un golpecito, y darle por saco al reso del piso, inclusive a la misma Olga.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item En el piso de Olga organizan fiestas esporádicamente, por lo que la
Acercarlo, ¿a qué?

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item María dedica la tarde de los domingos a escuchar música en su casa
Yo creo que estos dos apartados tendrías que ponerlos juntos. Son un user journey, de ahí ya sacarás las historias de usuario.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    equipo \emph{vintage}.
OK, en este caso queda claro el contexto. Pero se contradice un poco con lo que dices antes, de "un producto de menos de 349€". Se entiende que aquí lo único que tendría que comprar es un módulo NFC, ¿no?
También ten cuidado con estas cosas: si vas a programar el "servidor" y lo vas a hacer en Linux, tendrás que afinar mucho este HU para justificarlo.

2023-04-26 12:19 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    Para ello solo tendrá que acercar su Android hasta el altavoz en el que
NO veo mucha diferencia entonces con el tercer contexto. ¿No era la diferencia que ya tenía aparatos de automatización casera?

2023-04-27 11:49 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    \item María, 55 años, es audiófila desde pequeña y siempre le ha gustado
Quizás no se entienda aún el problema de los personajes en este apartado porque quería hacer un apartado que fuese presentación de personajes en el que se definiesen los dispositivos de cada uno y se presentasen sus habilidades. Sin entrar a comentar su viaje de usuario ni lo que espera. ([como esto](https://www.interaction-design.org/literature/article/personas-why-and-how-you-should-use-them) y [apartado "Personajes" en este artículo](https://www.linkedin.com/pulse/comenzando-con-un-trabajo-fin-de-gradom%25C3%25A1ster-%25C3%25A1gil-juan-j-merelo/?_l=es_ES)). 

¿"Mergeo" ambos apartados entonces en uno solo que haga de presentación + viaje?

2023-04-27 11:56 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    equipo \emph{vintage}.
La idea de poner coste inferior a 349€ es para un usuario que parta de 0. Es decir, un usuario que no tenga móvil, ni ordenador que ejecute el programa de recepción, ni lector NFC ni altavoces. De forma que comprar todo el equipo necesario siga sin superar el precio límite.

Para un usuario que ya posee móvil, ordenador viejo y altavoces, efectivamente lo único que necesita comprar un módulo de NFC.

2023-04-27 11:59 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    equipo \emph{vintage}.
> También ten cuidado con estas cosas: si vas a programar el "servidor" y lo vas a hacer en Linux, tendrás que afinar mucho este HU para justificarlo.

No entiendo esta parte. Si programo el servidor en Linux, pero luego ofrezco, por ejemplo, imágenes Docker para poder ejecutarlo en Windows o Mac, no debería haber problema no?

2023-04-28 10:59 UTC, migueorg commented on doc/secciones/01_introduccion.tex
>  \section{Descripción del Problema}
Corregido en [5a330bd](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/5a330bd3f9c2d1aea851125cd17f494c75b149fb)

2023-04-28 11:00 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +Otra opción sería emplear un asistente virtual (\emph{Alexa, Google Assistant,
Reestructurado en [8108727](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/81087274975c752f0811b38d3b3110de4b9b9e50)

2023-04-28 11:02 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +\emph{HomePod}.
En [e6dcf79](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/e6dcf79397cd1316acdc4eff76d47f757bcee71b) junto a la revisión del objetivo del precio he especificado y resumido un poco ese aspecto.

2023-04-28 11:05 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    reproduciendo en el dispositivo Android hasta el dispositivo que haga de
Quitado de ahí y de algunos párrafos más de los objetivos en los que aparecía en [9acf885](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/9acf885a66c6dc0168ebf08aa3b0b5ad8786a9b0). Aun así, la palabra Android sigue en otras partes del documento como la presentación, ya que el problema está centrado en Android, que es donde no existe una alternativa como la que se intenta hacer.

2023-04-28 11:06 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    el altavoz ha de poder realizarse sin interactuar con menús. (Se entiende
Eliminado en [982c623](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/982c62369ecc2da79f6e6cf2d2d5653cb8d2eb0d)

2023-04-28 11:07 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    \item El coste final del producto debe estar por debajo de los 349€, el cual
He intentado aclararlo un poco mejor en [e6dcf79](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/e6dcf79397cd1316acdc4eff76d47f757bcee71b) añadiendo un pequeño paréntesis aclaratorio en el objetivo, y añadiendo un párrafo extra en la motivación que resume el proyecto de forma más concreta pero sin entrar a detalles de implementación.

2023-04-28 11:31 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    Para ello solo tendrá que acercar su Android hasta el altavoz en el que
La diferencia es que Pepe tiene muchos _Alexa_ y similares, por lo que cuando le da al botón de compartir el podcast le aparecen muchos altavoces y es un lío buscar justo el que tiene enfrente dentro de una lista con tantos. 
María, sin embargo, solo quiere poder usar su antiguo equipo de altavoces con los servicios actuales de streaming, de una forma simple y barata.

Mientras tanto, piso de Olga busca una forma de encolar música nueva a la lista de reproducción actual sin que haya que usar el móvil del que tiene puesta la música en ese mismo momento. (Pero la verdad que este último usuario y viaje estoy pensando en borrarlos debido a la multitud de problemas que están generando los personajes)

2023-05-02 07:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    Para ello solo tendrá que acercar su Android hasta el altavoz en el que
> La diferencia es que Pepe tiene muchos _Alexa_ y similares, por lo que cuando le da al botón de compartir el podcast le aparecen muchos altavoces y es un lío buscar justo el que tiene enfrente dentro de una lista con tantos. María, sin embargo, solo quiere poder usar su antiguo equipo de altavoces con los servicios actuales de streaming, de una forma simple y barata.
>


Parece solo una diferencia cuantitativa. ¿Hay una diferencia en la lógica de negocio?
 
> Mientras tanto, piso de Olga busca una forma de encolar música nueva a la lista de reproducción actual sin que haya que usar el móvil del que tiene puesta la música en ese mismo momento. (Pero la verdad que este último usuario y viaje estoy pensando en borrarlos debido a la multitud de problemas que están generando los personajes)

Pero eso implicaría una lógica en el que recibe el stream, no en el que envía. ¿Vas a meterte en ese sarao? ¿Se pueden siquiera programar los altavoces de alguna forma?

En todo caso, no por los problemas, sino porque realmente no es un problema que tenga relación con la idea original, yo creo que habría que eliminarlo.

2023-05-04 09:53 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    Para ello solo tendrá que acercar su Android hasta el altavoz en el que
> Parece solo una diferencia cuantitativa. ¿Hay una diferencia en la lógica de negocio?

En la lógica de negocio no habría diferencia. La idea o crítica tras el personaje de Pepe es de alguna forma hacer ver que si los grandes fabricantes de altavoces inteligentes añadiesen este proyecto a sus dispositivos, o simplemente le añadiesen NFC, no habría que utilizar hardware externo para poder implementar esta solución, pues se podría usar también con sus altavoces "modernos".

> Pero eso implicaría una lógica en el que recibe el stream, no en el que envía. ¿Vas a meterte en ese sarao? ¿Se pueden siquiera programar los altavoces de alguna forma?

En la idea original que tenía en un principio sí que pensaba entrar ahí. Puesto que el servicio de recepción también lo voy a tener que hacer yo, no creía que añadir una cola fuese demasiado trabajo extra. Sin embargo, para no comprometerme a algo que todavía no conozco con certeza, y para no alargar más el proceso de documentación inicial, lo he eliminado en el commit [4947b9f](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/4947b9f8c8fcabc81b7b7b5e8091b19d949e5172). Ciñéndome así a un problema más atómico.

2023-05-04 09:55 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    \item María, 55 años, es audiófila desde pequeña y siempre le ha gustado
Mergeado en [4947b9f](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/4947b9f8c8fcabc81b7b7b5e8091b19d949e5172) para facilitar la lectura e introducción de los personajes y sus problemas.

2023-05-04 09:57 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    Para ello solo tendrá que acercar su Android hasta el altavoz en el que
Es mejor entonces que los pongas en un journey o en una sola historia de usuario. El objetivo de las historias de usuario es poder expresar bien los deseos de los usuarios para irlos priorizando en los milestones. Si dos usuarios dan lugar a la misma lógica de negocio, lo más fácil es fusionarlos en uno solo.

2023-05-04 11:01 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    Para ello solo tendrá que acercar su Android hasta el altavoz en el que
Fusionados en [f7b334d](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/f7b334dd46132f8d0bbea53480e860eee3f99f02)

2023-05-04 11:01 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    \item María dedica la tarde de los domingos a escuchar música en su casa
Hecho finalmente en [f7b334d](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/f7b334dd46132f8d0bbea53480e860eee3f99f02)

2023-05-04 11:02 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    \item El Piso de Olga es un grupo de jóvenes de entre 20 y 25 años que están
Eliminado en [4947b9f](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/4947b9f8c8fcabc81b7b7b5e8091b19d949e5172)

2023-05-04 11:03 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +    lo que quiere hacer de forma muy mascada para que le consigan entender
Fusionado y simplificado en [f7b334d](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/f7b334dd46132f8d0bbea53480e860eee3f99f02)

2023-05-05 10:44 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +poder brindar dicha sensación de continuidad al sistema operativo \emph{Android}
He intentado reescribir la motivación siguiendo esas pautas en [a35f3ae](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/a35f3aeae6063e88298f896d3dcf79f24dcab1d5). Adicionalmente, en el commit [e6dcf79](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/e6dcf79397cd1316acdc4eff76d47f757bcee71b) también se añadió un párrafo a la motivación con el fin de aclarar un poco más el proyecto.

2023-05-05 12:41 UTC, migueorg commented on doc/secciones/01_introduccion.tex
> +poder brindar dicha sensación de continuidad al sistema operativo \emph{Android}
Último retoque sobre este concepto añadido también en [cf2d179](https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/25/commits/cf2d179ab818a14e9a859c61d59b4c0c52ea04ea)

2023-05-10 07:42 UTC, JJ approved these changes
Yo creo que está bien para empezar. Se puede hacer algún cambio de detalle más adelante.

2023-05-15 19:15 UTC, merged