Desarrollo del estado del arte
migueorg/One-touch-music-streaming-TFG-ETSIIT pull request #34
Opened 2023-06-21 17:57 UTC by migueorg

En este PR se ha enfocado todo el trabajo en desarrollar y aclarar el estado del arte:

- Se ha diferenciado el propio estado del arte en diferentes secciones y subsecciones 3c6d7b24169c3d58fb222fc7780765635a7cb5f2
- Se ha explicado mejor la tecnología que hay tras la alternativa de Apple faa6e6de8e09e3d4b9b1f3083d4546a0ee1c81d8 (Con este commit se ha atendido al comentario https://github.com/migueorg/One-touch-music-streaming-TFG-ETSIIT/pull/15#discussion_r1194942333 el cual además estaba referenciado en el issue #33 )
- Se han desarrollado los primeros pasos de investigación en intentos de desarrollo del proyecto. 0b3574d496091888c3a4e09b9eb681d35bb33eb3, c7941509cc8b7d111d9f239aecba9e9d667f67ef y 701f81ed799d77e401c3f57f04ac57fde1465fff

Queda pendiente añadir algunas referencias a algunos términos y tecnologías para los cuales se han dejado un mensaje a modo de indicador que posteriormente será sustituido por la referencia.

El desarrollo de los primeros pasos de investigación e intentos de desarrollo (sección 2.3 en el PDF) se han añadido en el capítulo del estado del arte porque no tenía muy claro en que parte añadirlo, pero creo que encajaría mejor en el capítulo de la implementación.

2023-07-03 15:36 UTC, migueorg commented
@JJ listo para revisión :eyes:

(El commit 9761878c111c8bad34594420cb0ee9f9f4be61e1 ha sido para forzar la subida del commit 7bd5534be1fddc0290e913a2707485d12a362c39, el cual a pesar de haberle hecho push hace unos días, no aparecía en el cuerpo del PR.)

2023-07-03 15:52 UTC, JJ requested changes
Como tenemos tiempo, creo que es mejor que reorganices un poco el tema hablando de funcionalidades específicas (hardware cliente y servidor, transmisión de contenidos, APIs usadas, bibliotecas usadas) y de las diferentes opciones que hay. Ahora, aunque refleja claramente lo que sé de tu proceso de toma de decisiones, parece más un diario de a bordo que una sección de estado del arte, donde si no conoces exactamente en qué consiste el problema puedes estar un poco perdido. Dale una vueltecilla, por favor.

2023-07-03 15:52 UTC, JJ commented on doc/bibliografia.bib
> +@misc{GPIO,
Los artículos de la wikipedia los enlazaría directamente, la verdad. Usa la bibliografía para libros y artículos de revistas y así.

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\section{Análisis de las alternativas ya existentes}
Quita *ya*. Incluso *ya existentes*. Y cámbialo por alternativas a qué.

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
>  Otra opción sería emplear un asistente virtual (\emph{Alexa, Google Assistant,
¿Seguro que el nombre correcto de esto es "asistente virtual"? No es virtual, es físico.

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\subsection{Solución \emph{big techs}}
*de las* big tech (sin s)

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +El problema de esto es que se emplean chips específicos de \emph{Apple}, que
Si no es una solución abierta, y tampoco las tecnologías que se van a usar son aplicables, yo resumiría bastante esto.

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +uso de chips de \emph{UWB}.\\
Más que "sin" deberías de decir "con" qué... Requisitos mínimos (como bluetooth o WiFi)

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +con un simple gesto de proximidad. Es por esto que, con el fin de simplificar el
¿Por qué esos skills no permiten estas cosas? ¿No permiten "ver" la proximidad de otro dispositivo?

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +más permisivas en \emph{Android} que en \emph{iOS}, ya que estos últimos están
iOs ya lo habías descartado. Y quizás deberías hacer referencia a estas APIs antes de decir lo que hacen o no.

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +busca compensar a los usuarios de \emph{Android} que no han tenido ningún tipo
¿De qué solución estamos hablando? ¿De conectar un iPhone o iPad a Google Nest?

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Abordar el problema del empleo del chip \emph{Apple U1} ha sido la decisión más
NO hables de la tecnología, habla de lo que se pretende conseguir con esa tecnología.

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Valorando las alternativas al \emph{UWB} existentes en (al menos) la gran
Creo que te estás centrando en "alternativas a " las tecnologías. Y lo que creo que tendrías que explicar son las diferentes soluciones de esa tecnología y sustituirlas por una o por varias. Por lo que veo, estamos hablando 
1. Detección
2. Streaming y este a su vez en dos niveles: 
    1. Físico
    2. API

Y esto en emisor y en receptor. UWB consigue todo ello, junto con APIs privativas.  Tendrás que buscar alternativas físicas y tecnológicas explicando en ese orden cómo se hace, no "alternativas a UWB", que hace muchas cosas a la vez.

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Finalmente en el análisis de las alternativas al \emph{UWB} llegué al estudio
Como tengas a alguien de telecos en el tribunal aquí te salta al cuello. Es donde hablar de "alternativas" se rompe. Esto es una función que hace Apple usando esos chips, no sé como; que yo sepa, UWB no hace lo mismo que NFC ni incluye ninguna función parecida. Por eso tienes que dividir las funcionalidades en varias, añadiendo quizás "detección de presencia"

2023-07-03 15:52 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Tras dar unos pasos atrás se acabó replanteando el proyecto como un servicio en
Es muy pronto para decir lo que has andado hacia atrás o hacia delante; ahora mismo prácticamente no estás ni siquiera planteando el proyecto. Más adelante puedes plantearlo, pero aquí lo que diría son las diferentes posibilidades que hay para más adelante, cuando hables de implementación, escoger una. Recuerda que es el estado del arte.

2023-07-05 18:10 UTC, migueorg commented on doc/bibliografia.bib
> +@misc{GPIO,
Como quedarían mejor, ¿enlazarlos usando un pie de página o mediante hipervínculos?

2023-07-05 18:12 UTC, JJ commented on doc/bibliografia.bib
> +@misc{GPIO,
Si quieres añadir algo, pie de página. En cualquier caso, hipervínculos. Hoy en día ya todo el mundo maneja PDFs.

2023-09-20 15:07 UTC, migueorg commented on doc/bibliografia.bib
> +@misc{GPIO,
Corregido en 461b325a43bb891fa6b4f81a2bc1ab86df7266b4

2023-09-20 15:08 UTC, migueorg commented on doc/secciones/03_estado_del_arte.tex
> +\subsection{Solución \emph{big techs}}
Este y el resto de errores en el nombrado de subsecciones han sido arreglados en 15e107084c1850793fb8afccc211bfba80e7445f

2023-09-20 15:09 UTC, migueorg commented on doc/secciones/03_estado_del_arte.tex
> +El problema de esto es que se emplean chips específicos de \emph{Apple}, que
Resumido en 616e075ff369369288905e93dd833597c989df45

2023-09-20 15:10 UTC, migueorg commented on doc/secciones/03_estado_del_arte.tex
> +uso de chips de \emph{UWB}.\\
Reformulado en f085cec94028288ff3656c6eef872debbce58bc0

2023-09-20 15:11 UTC, migueorg commented on doc/secciones/03_estado_del_arte.tex
> +más permisivas en \emph{Android} que en \emph{iOS}, ya que estos últimos están
Referenciado en c3acdc3762c15e7c2dc78a6180c5d3dac9cf4651

2023-09-20 15:19 UTC, migueorg commented
He eliminado del estado del arte los detalles sobre los intentos de implementación que han ido ocurriendo durante el desarrollo, para más adelante documentarlos en otro apartado de la documentación. La mayoría de los problemas estaban en esa parte, ya que hacían que el estado del arte se desviase de sus intenciones originales.

2023-09-20 15:46 UTC, JJ commented
> He eliminado del estado del arte los detalles sobre los intentos de implementación que han ido ocurriendo durante el desarrollo, para más adelante documentarlos en otro apartado más apropiado de la documentación. La mayoría de los problemas estaban en esa parte, ya que hacían que el estado del arte se desviase de sus intenciones originales.

OK, me parece una buena idea.

2023-09-21 08:42 UTC, merged