Primeras clases. Ports y Adapters
migueorg/One-touch-music-streaming-TFG-ETSIIT pull request #58
Opened 2023-10-25 12:12 UTC by migueorg

En este PR:

- Se han limpiado los restos de JavaScript existentes en la plantilla del repositorio 682553c
- Se ha reestructurado varias veces la localización del código buscando la forma más óptima de agrupar los diferentes módulos y lenguajes del mismo f9ee8c80c59dd4f6732e322c4ac0cfd838fbe047, 68656c7f1c5d0f514bad81467087ffe8109f42c8 y ee5c1b737112b3be49d0c4e630bd9b54f95c215d
- Se han creado los _Ports_ y _Adapters_ para el módulo NFC en Python del receptor. 68656c7f1c5d0f514bad81467087ffe8109f42c8
- Se ha separado el módulo de NFC y el de streaming de audio como módulos independientes. ee5c1b737112b3be49d0c4e630bd9b54f95c215d
- Se ha llevado a cabo un proceso de selección para elegir el lenguaje que más se adecúa para el streaming del audio. 4c6f6194c7522ebd4fbd1796d5de79930b90b74b  
- Se han creado los _Ports_ y _Adapters_ para el módulo de audio en streaming en Java del receptor. 40c91b285d2cf3f61f58f316b96016c0ca1581f0
- Se ha creado y añadido el proyecto vacío de Kotlin generado con Android Studio. 95cd3bb399b9edfb3cecc6ce0ef402a5285d13d8
- Se han añadido los _Ports_ y _Adapters_ para la captura de audio, envío de audio y lectura de NFC en Android. 8950a7f1a8ad5923242d6a614f5fbc2ab752d767

Este PR cierra el issue: #55
Este PR avanza los issues: #57 #51 #52 #53 y #54

Adicionalmente, se ha creado el issue #57 que establece los requisitos para cerrar el Milestone 1.

2023-10-26 15:19 UTC, JJ requested changes
Los ficheros `.idea` no deben estar en el repo. El resto, has incluido algún ejemplo, no sé si hará falta que estén.

2023-10-26 15:19 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +    \item Se valorará la sencillez en cuanto instalación del lenguaje en modo \emph{headless}.
¿Textidote ha pasado esto? Sería *a* instalación, ¿no?

2023-10-26 15:19 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +    \item Se valorará la simpleza en cuanto a ejecución de los archivos ejecutables.
*simplicidad* Simpleza es de ánimo.

2023-10-26 15:19 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +    \item Para instalar Kotlin, dado que es un lenguaje mucho más moderno que
En cualquier lenguaje deberías usar un gestor de versiones. NO sé si hay algo así para Java y Kotlin, pero se trata de que uses la versión que quieras usar en cada momento, no la que haya en los repos.

2023-10-26 15:19 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Para capturar y enviar el audio desde la parte de Android se emplean bibliotecas
Hay otros lenguajes: groovy, por ejemplo. No es muy popular, pero existe...

2023-10-31 10:42 UTC, migueorg commented on doc/secciones/06_implementacion.tex
> +    \item Se valorará la sencillez en cuanto instalación del lenguaje en modo \emph{headless}.
Extraño que Textidote no se haya quejado, pero sí, estaba mal. Corregido en bd8685ed7ee4c863da6718a19bf2b070f21b2303

2023-10-31 10:45 UTC, migueorg commented on doc/secciones/06_implementacion.tex
> +    \item Para instalar Kotlin, dado que es un lenguaje mucho más moderno que
Totalmente de acuerdo con el uso específico de versiones en lugar de `latest`. Por ahorrar texto no lo había especificado pero se ha añadido y tenido en cuenta en bd8685ed7ee4c863da6718a19bf2b070f21b2303

2023-10-31 10:46 UTC, migueorg commented on doc/secciones/06_implementacion.tex
> +Para capturar y enviar el audio desde la parte de Android se emplean bibliotecas
He refinado los criterios de búsqueda y selección, así como las alternativas encontradas en bd8685ed7ee4c863da6718a19bf2b070f21b2303

2023-11-03 12:32 UTC, migueorg commented
- He eliminado los archivos que se habían colado de .idea y he actualizado el .gitignore con un par de archivos y directorios más a tener en cuenta. b7d892474000ef148b715d281af0316ddeede27b
- Le he dado una vuelta al proceso de selección, modificando un poco los criterios de busqueda y los de selección y añadiendo algunos candidatos así como el uso de versiones específicas para los lenguajes, cosas que había pasado por alto. bd8685ed7ee4c863da6718a19bf2b070f21b2303 
- He arreglado algunos fallos ortográficos 

Y sobre los ejemplos que he mantenido los he añadido a conciencia para que Android Studio me automatice ciertas acciones que más adelante tendría que hacer manualmente.

Por lo que considero que estaría listo para revisión @JJ

2023-11-03 18:07 UTC, JJ approved these changes
Argh, 49 ficheros. Voy a fiarme. Veo que hay tests, una buena modularización, parece que se siguen las buenas prácticas, así que adelante.

2023-11-05 11:40 UTC, merged